name: 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 Run 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dep
        run:
          python3 -m pip install --upgrade pip
          pip install pytest

      - name: Unittest
        shell: bash
        run:
          pytest TestTree.py
